Algoritmo "Sucessor"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicita um valor e exibe o seu sucessor
// Autor(a)    : Obama
// Data atual  : 02/09/2024
Var
// Seção de Declarações das variáveis
numero,resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um número :")
Leia(numero)
resultado<-numero+1
Escreval("O sucessor do número digitado é : ",resultado)

Fimalgoritmo